### ISSUE TITLE
database of only irrelevant compounds

### ISSUE THREAD

**Issue by rwehrens** [rwehrens/metaMS#4]
Suppose you have a couple of blank samples and no DB - you'd probably want to eliminate all spectra found in the blanks from the data. Works fine if you have a DB - if you don't and you create a DB from all spectra in the blanks (but nothing else) then the matching with the database throws an error.

Solution: add a check if the number of entries in the DB is larger than zero (after removing the irrelevants). Will add this as soon as Bioconductor completes the switch to git. In matchSamples2DB we need to check (in addition??) if rt.matches > 0

**Comment by jsaintvanne** [comment]
Have the same problem actually during my tests... It is not due to blank or something but just tried to compare a DB of something with files from something else! And of course 0 matches but not expected : this error...

We should add a verification step with rt.matches because actually we obtain this error `Error in rt.matches[[ii]][i, 1] : subscript out of bounds`
It is because nothing matched between DB and files (I think)

I'm working on it and will probably propose a new PR to be able to correct it !

@yguitton
